### ISSUE TITLE
Remove log.json and journal entry if instance is deleted

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-backend#19]
If an instance is removed, remove also...
* the json file /srv/openslides/instances/openslides_instance_*.log.json
* the entry in openslides_instance.journal

**Comment by emanuelschuetze** [comment]
Split out "entry in openslides_instance.journal" in #33

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
