### ISSUE TITLE
Allow to install OpenSlides plugins

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-backend#20]
Currently there is no possibility to install a OpenSlides plugin to an existing rkt container. It would be nice to install a selected plugin via the OpenSlides Manager gui.

Workaround: Adapt the Dockerfile and download/install a plugin while build the image, see e.g.:
https://github.com/Intevation/OpenSlides/commit/ea272b05abbcd351aa996ef32a7c0f2383feec7c

**Comment by emanuelschuetze** [comment]
Suggestion to install a plugin easily:

Manually steps:
1. Copy plugin directory to instance directory, e.g.:
/srv/openslides/instances/67482905df204a7f9b9163f96d3fa080/plugins/openslides_votecollector
('plugins' should be created as empty directory by default)

2. Add plugin name to settings.py, e.g.:
/srv/openslides/instances/67482905df204a7f9b9163f96d3fa080/settings.py
```
INSTALLED_PLUGINS += (
    'openslides_votecollector',
}
INSTALLED_APPS += INSTALLED_PLUGINS
```
-> settings template should be extended that only the plugin name can replaced.

3. Now stop and restart instance via OpenSlides Manager interface.

Now the Manager backend should do the following steps autmatically:
4. Copy plugin directory
   `cp -r /data/plugins/* /app/`
5. Run migration
   `cd /app && python manage.py migrate`
6. Run collectstatic
   `python manage.py collectstatic`


@boehlke What do you think? Can you implement step (4) to (6)?

**Comment by boehlke** [comment]
- Step 4... should not be needed because we would mount the plugin directory directly into /app/plugins
- Step 5+6: This can be done easily, we can add a button in the UI for this.

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
