### ISSUE TITLE
Collectstatic command failed (because "pod ... isn't currently running")

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-backend#22]
After upgrading an instance sometimes(!) the collectstatic command failed because rkt pod isn't currently running:

```
     ...
           "cmd": [
                "/usr/bin/rkt", 
                "enter", 
                "7c660498-2977-4f69-95e3-92798ac6bd6a", 
                "/app/manage.py", 
                "collectstatic", 
                "--noinput", 
                "--clear"
            ], 
            "rc": 254, 
            "start": "2017-10-06 10:49:57.138700", 
            "stderr": "enter: pod \"7c660498-2977-4f69-95e3-92798ac6bd6a\" isn't currently running", 
   ...
```

Run the command manually helps.

**Comment by emanuelschuetze** [comment]
Reproduceable if you upgrade two (or more) instances in the same time.

**Comment by boehlke** [comment]
The new wait-ready option in "rkt status" might help:
https://github.com/rkt/rkt/blob/master/Documentation/subcommands/status.md
I will work this into the ansible scripts.

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
