### ISSUE TITLE
Unnecessary database restarts

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-multiinstance-backend#23]
The `openslides-add-instance` role restarts both Redis and Postgres every time a new instance is created, see `/roles/openslides-add-instance/tasks/init_instance_database.yml:30`.

The restarts became a problem when we disabled Redis' persistence.

The reason given for both tasks is "to make sure it bind to veth ip" which makes it sound like a hack.  Fortunately, they don't seem to be necessary at all as far as I can see.  Could they be removed?

**Comment by boehlke** [comment]
I am not sure, could you just try this? There was a reason why I built this in...

**Comment by emanuelschuetze** [comment]
@gsiv As discussed with @boehlke please create a pull request and test the restart.

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
