### ISSUE TITLE
Allow two different configurations (for worker, daphnes)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-backend#28]
Provide the configuration in create form via drop down list.
Use e.g. a configuration for events with <100 particiants (4 worker, 1 daphne) and >= 100 participants (8 worker, 2 daphnes).

**Comment by FinnStutzenstein** [comment]
The instance "daphne" on openslides-multi is now configured to run with two daphnes. Do not start and stop this instance in fact that the current backend implementation would create different systend units and override my changes.

Steps for setting up multiple daphes:
- Make more ports exposed in the docker image. Do a fixed number of ports (imho 8 is good) thus we do not want to build images for every variable number of daphnes.
- Do not reserve 2 ports for every instance anymore. With support for up to 8 daphnes, reserve 16 ports per instance. These are 8 pairs of ports for the communication between nginx<->systemd and systemd<->rkt.
- Add this to the nginx instance config:
```
upstream openslides_a9a74e8ba05c40b395ca06a909081b62 {
    server localhost:23294;
    server localhost:25000;
}
```
- Change `proxy_pass` to `http://openslides_a9a74e8ba05c40b395ca06a909081b62/;`. Reload nginx.
- Update the supervisord.conf to spawn multiple daphnes on ports 8001, 8002, ...
- Rename the `openslides_instance_proxy_<uuid>_.service` to `openslides_instance_proxy_<uuid>_daphne_x.service`. Same for the `.socket` files. For more than one daphne just copy-paste the file, change the name and the ports in the files.
- Edit the `openslides_instance_<uuid>.service` and pass all used ports to the rocket container.
- Enable the new created sockets with `systemctl enbale`. Disable the old one.
- Make sure the old service has stopped and make a `systemctl daemon-reload`.
- Start all new sockets and services. Also restart the `openslides_instance_<uuid>.service` so the container updates and starts all daphnes.

Hopefully, I didn't forget anything :)

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
