### ISSUE TITLE
Improve 502 page

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-backend#29]
- check state request on instance (running, stopped, error, installing, sleeping...)
- show information depends on state

**Comment by FinnStutzenstein** [comment]
THe most common situation is the following: The user gets the 502 page, but the sate shown in the multiinstance frontend is active. If this happens my proposal would be to show something like "Could not reach the OpenSlides instance <name>" with a retry-button. If the status is sleeping, starting, installing, error or removed a suitable message would be shown.
@emanuelschuetze OK?

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
