### ISSUE TITLE
Update instance Nginx template: SPDY vs. HTTP2 module

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-multiinstance-backend#38]
The Ansible template `nginx_instance_subdomain.conf.j2` generates Nginx configuration files requiring the SPDY module ([ngx_http_spdy_module](https://nginx.org/en/docs/http/ngx_http_spdy_module.html)):

https://github.com/OpenSlides/openslides-multiinstance-backend/blob/67b69881e5905e1f381f7825776411c7514531ad/roles/openslides-add-instance/templates/nginx_instance_subdomain.conf.j2#L15-L16

This works with Nginx versions < 1.9.5.  With version 1.9.5 the module has been superseded by [ngx_http_v2_module](https://nginx.org/en/docs/http/ngx_http_v2_module.html) which requires the `listen` directive to not use `spdy` but `http2`.

Debian Stretch installations are affected by this change, for example.

I think we should verify whether we need HTTP2 in those configurations at all.  If we do, the Ansible playbook should generate templates accordingly because both Debian Jessie and Stretch should be supported by the backend for now.

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
